/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/0033.glb -o public/002.jsx -T 
Files: public/0033.glb [1.6MB] > C:\Y2K-LO-FI\sunset\public\0033-transformed.glb [115.63KB] (93%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/0033-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[50.408, -1.645, 7.673]} rotation={[0, 0.087, 0]} scale={2.073}>
          <group name="root">
            <group name="hips" position={[0, 0.85, 0]}>
              <group name="spine" position={[0, 0.159, 0]}>
                <group name="chest" position={[0, 0.12, 0]}>
                  <group name="neck" position={[0, 0.288, 0]}>
                    <group name="head" position={[0, 0.142, 0]}>
                      <group name="eyeL" position={[0.028, 0.035, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
                      <group name="eyeR" position={[-0.028, 0.035, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
                    </group>
                  </group>
                  <group name="shoulderL" position={[0.025, 0.287, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                    <group name="upper_armL" position={[0, 0.08, 0]}>
                      <group name="lower_armL" position={[0, 0.319, 0]}>
                        <group name="handL" position={[0, 0.255, 0]}>
                          <group name="thumb_proximalL" position={[0.03, 0, 0]} rotation={[0, 0, -Math.PI / 4]}>
                            <group name="thumb_intermediateL" position={[0, 0.034, 0]}>
                              <group name="thumb_distalL" position={[0, 0.026, 0]} />
                            </group>
                          </group>
                          <group name="index_proximalL" position={[0.03, 0.08, 0]}>
                            <group name="index_intermediateL" position={[0, 0.029, 0]}>
                              <group name="index_distalL" position={[0, 0.022, 0]} />
                            </group>
                          </group>
                          <group name="middle_proximalL" position={[0.01, 0.08, 0]}>
                            <group name="middle_intermediateL" position={[0, 10, 0]}>
                              <group name="middle_distalL" position={[0, 0.026, 0]} />
                            </group>
                          </group>
                          <group name="ring_proximalL" position={[-0.01, 0.08, 0]}>
                            <group name="ring_intermediateL" position={[0, 0.029, 0]}>
                              <group name="ring_distalL" position={[0, 0.022, 0]} />
                            </group>
                          </group>
                          <group name="little_proximalL" position={[-0.03, 0.08, 0]}>
                            <group name="little_intermediateL" position={[0, 0.022, 0]}>
                              <group name="little_distalL" position={[0, 0.017, 0]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="shoulderR" position={[-0.025, 0.287, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
                    <group name="upper_armR" position={[0, 0.08, 0]}>
                      <group name="lower_armR" position={[0, 0.319, 0]}>
                        <group name="handR" position={[0, 0.255, 0]}>
                          <group name="thumb_proximalR" position={[-0.03, 0, 0]} rotation={[0, 0, Math.PI / 4]}>
                            <group name="thumb_intermediateR" position={[0, 0.034, 0]}>
                              <group name="thumb_distalR" position={[0, 0.026, 0]} />
                            </group>
                          </group>
                          <group name="index_proximalR" position={[-0.03, 0.08, 0]}>
                            <group name="index_intermediateR" position={[0, 0.029, 0]}>
                              <group name="index_distalR" position={[0, 0.022, 0]} />
                            </group>
                          </group>
                          <group name="middle_proximalR" position={[-0.01, 0.08, 0]}>
                            <group name="middle_intermediateR" position={[0, 0.034, 0]}>
                              <group name="middle_distalR" position={[0, 0.026, 0]} />
                            </group>
                          </group>
                          <group name="ring_proximalR" position={[0.01, 0.08, 0]}>
                            <group name="ring_intermediateR" position={[0, 0.029, 0]}>
                              <group name="ring_distalR" position={[0, 0.022, 0]} />
                            </group>
                          </group>
                          <group name="little_proximalR" position={[0.03, 0.08, 0]}>
                            <group name="little_intermediateR" position={[0, 0.022, 0]}>
                              <group name="little_distalR" position={[0, 0.017, 0]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="upper_legL" position={[0.053, 0.08, 0]} rotation={[Math.PI, 0, 0]}>
                <group name="lower_legL" position={[0, 0.422, 0]}>
                  <group name="footL" position={[0, 0.422, 0]} rotation={[-1.115, 0, 0]}>
                    <group name="toesL" position={[0, 0.193, 0]} rotation={[2.686, 0, Math.PI]} />
                  </group>
                </group>
              </group>
              <group name="upper_legR" position={[-0.053, 0.08, 0]} rotation={[Math.PI, 0, 0]}>
                <group name="lower_legR" position={[0, 0.422, 0]}>
                  <group name="footR" position={[0, 0.422, 0]} rotation={[-1.115, 0, 0]}>
                    <group name="toesR" position={[0, 0.193, 0]} rotation={[2.686, 0, Math.PI]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={nodes.Circle008.material} position={[-619.213, 9.482, -279.828]} rotation={[Math.PI / 2, 0, -1.34]} scale={48.511} />

        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.PaletteMaterial002} position={[25.185, -1.645, 20.551]} scale={92.63} />

        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.PaletteMaterial002} position={[74.838, -1.645, -5.613]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.034} />
        
        <mesh name="BézierCircle001" geometry={nodes.BézierCircle001.geometry} material={materials.PaletteMaterial003} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.PaletteMaterial006} position={[30.342, -1.646, 12.106]} rotation={[0, 0.763, 0]} scale={0.219} />
        <mesh name="bady" geometry={nodes.bady.geometry} material={materials.PaletteMaterial004} position={[30.574, 1.189, 11.866]} rotation={[-Math.PI, -0.85, -Math.PI]} scale={0.077} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials.PaletteMaterial005} position={[30.536, 0.501, 11.745]} rotation={[-Math.PI, 0.808, -Math.PI]} scale={[0.022, 0.022, 0.029]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.PaletteMaterial007} position={[30.277, 1.9, 11.047]} rotation={[0, 0.763, -Math.PI / 2]} scale={0.219} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Material.035']} position={[30.585, 0.429, 11.815]} rotation={[Math.PI / 2, 0, -2.334]} scale={[0.095, 0.031, 0.031]} />
        <mesh name="SCREEN" geometry={nodes.SCREEN.geometry} material={materials['Material.041']} position={[30.593, 1.257, 11.844]} rotation={[-Math.PI, -0.85, -Math.PI]} scale={0.077} />
      </group>
    </group>
  )
}

useGLTF.preload('/0033-transformed.glb')
