/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Home.glb -o src/components/three/Home.jsx -T 
Files: public/Home.glb [1.6MB] > C:\Y2K-LO-FI\sunset\src\components\three\Home-transformed.glb [119.66KB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'


export function Model(props) {

  const camRef = useRef()



  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Home-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[53.453, -1.56, 8.145]} rotation={[0, 0.087, 0]} scale={2.073}>
          <group name="root">
            <group name="hips" position={[0, 0.85, 0]}>
              <group name="spine" position={[0, 0.159, 0]}>
                <group name="chest" position={[0, 0.12, 0]}>
                  <group name="neck" position={[0, 0.288, 0]}>
                    <group name="head" position={[0, 0.142, 0]}>
                      <group name="eyeL" position={[0.028, 0.035, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
                      <group name="eyeR" position={[-0.028, 0.035, 0]} rotation={[-Math.PI / 2, 0, Math.PI]} />
                    </group>
                  </group>
                  <group name="shoulderL" position={[0.025, 0.287, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                    <group name="upper_armL" position={[0, 0.08, 0]}>
                      <group name="lower_armL" position={[0, 0.319, 0]}>
                        <group name="handL" position={[0, 0.255, 0]}>
                          <group name="thumb_proximalL" position={[0.03, 0, 0]} rotation={[0, 0, -Math.PI / 4]}>
                            <group name="thumb_intermediateL" position={[0, 0.034, 0]}>
                              <group name="thumb_distalL" position={[0, 0.026, 0]} />
                            </group>
                          </group>
                          <group name="index_proximalL" position={[0.03, 0.08, 0]}>
                            <group name="index_intermediateL" position={[0, 0.029, 0]}>
                              <group name="index_distalL" position={[0, 0.022, 0]} />
                            </group>
                          </group>
                          <group name="middle_proximalL" position={[0.01, 0.08, 0]}>
                            <group name="middle_intermediateL" position={[0, 0.034, 0]}>
                              <group name="middle_distalL" position={[0, 0.026, 0]} />
                            </group>
                          </group>
                          <group name="ring_proximalL" position={[-0.01, 0.08, 0]}>
                            <group name="ring_intermediateL" position={[0, 0.029, 0]}>
                              <group name="ring_distalL" position={[0, 0.022, 0]} />
                            </group>
                          </group>
                          <group name="little_proximalL" position={[-0.03, 0.08, 0]}>
                            <group name="little_intermediateL" position={[0, 0.022, 0]}>
                              <group name="little_distalL" position={[0, 0.017, 0]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="shoulderR" position={[-0.025, 0.287, 0]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
                    <group name="upper_armR" position={[0, 0.08, 0]}>
                      <group name="lower_armR" position={[0, 0.319, 0]}>
                        <group name="handR" position={[0, 0.255, 0]}>
                          <group name="thumb_proximalR" position={[-0.03, 0, 0]} rotation={[0, 0, Math.PI / 4]}>
                            <group name="thumb_intermediateR" position={[0, 0.034, 0]}>
                              <group name="thumb_distalR" position={[0, 0.026, 0]} />
                            </group>
                          </group>
                          <group name="index_proximalR" position={[-0.03, 0.08, 0]}>
                            <group name="index_intermediateR" position={[0, 0.029, 0]}>
                              <group name="index_distalR" position={[0, 0.022, 0]} />
                            </group>
                          </group>
                          <group name="middle_proximalR" position={[-0.01, 0.08, 0]}>
                            <group name="middle_intermediateR" position={[0, 0.034, 0]}>
                              <group name="middle_distalR" position={[0, 0.026, 0]} />
                            </group>
                          </group>
                          <group name="ring_proximalR" position={[0.01, 0.08, 0]}>
                            <group name="ring_intermediateR" position={[0, 0.029, 0]}>
                              <group name="ring_distalR" position={[0, 0.022, 0]} />
                            </group>
                          </group>
                          <group name="little_proximalR" position={[0.03, 0.08, 0]}>
                            <group name="little_intermediateR" position={[0, 0.022, 0]}>
                              <group name="little_distalR" position={[0, 0.017, 0]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="upper_legL" position={[0.053, 0.08, 0]} rotation={[Math.PI, 0, 0]}>
                <group name="lower_legL" position={[0, 0.422, 0]}>
                  <group name="footL" position={[0, 0.422, 0]} rotation={[-1.115, 0, 0]}>
                    <group name="toesL" position={[0, 0.193, 0]} rotation={[2.686, 0, Math.PI]} />
                  </group>
                </group>
              </group>
              <group name="upper_legR" position={[-0.053, 0.08, 0]} rotation={[Math.PI, 0, 0]}>
                <group name="lower_legR" position={[0, 0.422, 0]}>
                  <group name="footR" position={[0, 0.422, 0]} rotation={[-1.115, 0, 0]}>
                    <group name="toesR" position={[0, 0.193, 0]} rotation={[2.686, 0, Math.PI]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <PerspectiveCamera name="Camera_LOGIN" makeDefault={true} far={1013} near={0.1} fov={25} position={[13.663, -0.027, -2.681]} rotation={[0.169, 2, 2.7]} />
        <PerspectiveCamera name="Camera_MENU" makeDefault={false} far={1013} near={0.1} fov={14.426} position={[48.263, 2.511, 7.119]} rotation={[-3.02, 0.798, 3.059]} />
        <PerspectiveCamera name="Camera_B" makeDefault={false} far={1013} near={0.1} fov={14.426} position={[100, 30, 55]} rotation={[-0.003, 1, 0.007]} scale={2.034} />
        <PerspectiveCamera name="Camera_A" makeDefault={false} far={1013} near={0.1} fov={15} position={[91.551, -0.325, 28.667]} rotation={[0.207, 1.159, -0.185]} scale={2.034} />
        <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={nodes.Circle008.material} position={[-516.312, -15.475, -217.289]} rotation={[Math.PI / 2, 0, -1.283]} scale={65.701} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.PaletteMaterial001} position={[25.134, -1.413, 20.699]} scale={92.63} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.PaletteMaterial002} position={[77.882, -1.564, -5.141]} rotation={[-Math.PI, 0, -Math.PI]} scale={2.034} />

        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.PaletteMaterial006} position={[36.848, -1.413, 16.13]} rotation={[0, 0.763, 0]} scale={0.219} />
        <mesh name="bady" geometry={nodes.bady.geometry} material={materials.PaletteMaterial004} position={[37.081, 1.422, 15.89]} rotation={[-Math.PI, -0.85, -Math.PI]} scale={0.077} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials.PaletteMaterial005} position={[37.043, 0.734, 15.77]} rotation={[-Math.PI, 0.808, -Math.PI]} scale={[0.022, 0.022, 0.029]} />
        <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials.PaletteMaterial007} position={[36.784, 2.133, 15.072]} rotation={[0, 0.763, -Math.PI / 2]} scale={0.219} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Material.035']} position={[37.092, 0.662, 15.84]} rotation={[Math.PI / 2, 0, -2.334]} scale={[0.095, 0.031, 0.031]} />
        <mesh name="SCREEN" geometry={nodes.SCREEN.geometry} material={materials['Material.041']} position={[37.1, 1.49, 15.869]} rotation={[-Math.PI, -0.85, -Math.PI]} scale={0.077} />
      </group>
    </group>
  )
}

useGLTF.preload('/Home-transformed.glb')
